// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android; // <-- Fixed here: return android options
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGcL2VsSmXkaiONw7Q2zPgxfKNACOK53c',
    appId: '1:825794088538:web:663087905acf8a7b00d263',
    messagingSenderId: '825794088538',
    projectId: 'salonix-learning',
    authDomain: 'salonix-learning.firebaseapp.com',
    storageBucket: 'salonix-learning.firebasestorage.app',
    measurementId: 'G-HV0PRRH2M6',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL9W4aE8re9KVtprN1BDEN200RgksMXa4',
    appId: '1:825794088538:ios:dc1566b8274245a700d263',
    messagingSenderId: '825794088538',
    projectId: 'salonix-learning',
    storageBucket: 'salonix-learning.firebasestorage.app',
    androidClientId:
        '825794088538-drfh1rne940bfhngba9hdm0vvjg51ss7.apps.googleusercontent.com',
    iosClientId:
        '825794088538-dnc22co2p9m45n3grt86td0b8efmokr9.apps.googleusercontent.com',
    iosBundleId: 'com.example.salonix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL9W4aE8re9KVtprN1BDEN200RgksMXa4',
    appId: '1:825794088538:ios:dc1566b8274245a700d263',
    messagingSenderId: '825794088538',
    projectId: 'salonix-learning',
    storageBucket: 'salonix-learning.firebasestorage.app',
    androidClientId:
        '825794088538-drfh1rne940bfhngba9hdm0vvjg51ss7.apps.googleusercontent.com',
    iosClientId:
        '825794088538-dnc22co2p9m45n3grt86td0b8efmokr9.apps.googleusercontent.com',
    iosBundleId: 'com.example.salonix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGcL2VsSmXkaiONw7Q2zPgxfKNACOK53c',
    appId: '1:825794088538:web:d91394d34999744900d263',
    messagingSenderId: '825794088538',
    projectId: 'salonix-learning',
    authDomain: 'salonix-learning.firebaseapp.com',
    storageBucket: 'salonix-learning.firebasestorage.app',
    measurementId: 'G-2ZSFBV152C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeXXw7f_h0x5TEFpWYeUkqbOsO3mbYwAg',
    appId: '1:825794088538:android:acd245bf664e319d00d263',
    messagingSenderId: '825794088538',
    projectId: 'salonix-learning',
    storageBucket: 'salonix-learning.firebasestorage.app',
  );
}
